using System.Numerics;
using SpaceBattle.Actions;
using SpaceBattle.Commands;

namespace SpaceBattle.Adapter
{
    public class AutoGeneratedMovableAdapter : IMovable
    {
        private readonly IMovable movableAdapter;

        private readonly IResolvable ioC;

        public AutoGeneratedMovableAdapter(IMovable movableAdapter, IResolvable ioC)
        {
            this.movableAdapter = movableAdapter;
            this.ioC = ioC;
        }

        public Vector2 Position
        {
            get => ioC.Resolve<Vector2>("Object.GetPosition", movableAdapter);
            set => ioC.Resolve<ICommand>("Object.SetPosition", movableAdapter, value).Execute();
        }

        public Vector2 Velocity => ioC.Resolve<Vector2>("Object.GetVelocity", movableAdapter);
    }
}