name: PatternsCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      working-directory: ./MainPatterns_24_03/
      run: dotnet restore
    - name: Build
      working-directory: ./MainPatterns_24_03/
      run: dotnet build
    - name: Test
      working-directory: ./MainPatterns_24_03/
      run: dotnet test
